import { HTTPException } from 'hono/http-exception'
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import QRCode from 'qrcode'
import * as batchQueries from '../db/queries/batches.js'
import * as qrcodeQueries from '../db/queries/qrcodes.js'
import * as productQueries from '../db/queries/products.js'

// A4 dimensions in points (1 point = 1/72 inch)
const A4_WIDTH = 595.28
const A4_HEIGHT = 841.89
const MARGIN = 56.69 // ~20mm
const QR_SIZE = 90
const LABEL_HEIGHT = 14
const COLS = 4
const ROWS = 5
const ITEMS_PER_PAGE = COLS * ROWS
const COL_SPACING = (A4_WIDTH - 2 * MARGIN - COLS * QR_SIZE) / (COLS - 1)
const ROW_SPACING = (A4_HEIGHT - 2 * MARGIN - 40 - ROWS * (QR_SIZE + LABEL_HEIGHT + 8)) / (ROWS - 1)

export async function generatePdf(batchId: string): Promise<Buffer> {
  // Fetch batch + product info
  const batch = await batchQueries.findById(batchId)
  if (!batch) {
    throw new HTTPException(404, { message: 'Batch not found' })
  }

  if (!batch.is_locked) {
    throw new HTTPException(400, {
      message: 'QR codes have not been generated for this batch yet'
    })
  }

  const product = await productQueries.findById(batch.product_id)
  const qrCodes = await qrcodeQueries.findAllByBatchId(batchId)

  if (qrCodes.length === 0) {
    throw new HTTPException(404, { message: 'No QR codes found for this batch' })
  }

  const frontendBaseUrl = process.env.FRONTEND_BASEURL || 'http://localhost:3000'
  const pdfDoc = await PDFDocument.create()
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  const totalPages = Math.ceil(qrCodes.length / ITEMS_PER_PAGE)

  for (let pageIndex = 0; pageIndex < totalPages; pageIndex++) {
    const page = pdfDoc.addPage([A4_WIDTH, A4_HEIGHT])
    const pageQrCodes = qrCodes.slice(
      pageIndex * ITEMS_PER_PAGE,
      (pageIndex + 1) * ITEMS_PER_PAGE
    )

    // Header
    page.drawText(`${product?.name || 'Product'} — Batch: ${batch.batch_number}`, {
      x: MARGIN,
      y: A4_HEIGHT - MARGIN + 10,
      size: 10,
      font: boldFont,
      color: rgb(0.2, 0.2, 0.2)
    })

    // Draw QR codes in grid
    for (let i = 0; i < pageQrCodes.length; i++) {
      const col = i % COLS
      const row = Math.floor(i / COLS)

      const x = MARGIN + col * (QR_SIZE + COL_SPACING)
      const y = A4_HEIGHT - MARGIN - 30 - row * (QR_SIZE + LABEL_HEIGHT + 8 + ROW_SPACING)

      // Generate QR code PNG
      const verifyUrl = `${frontendBaseUrl}/verify?sn=${pageQrCodes[i].serial_number}`
      const qrBuffer = await QRCode.toBuffer(verifyUrl, {
        type: 'png',
        width: QR_SIZE * 3, // 3x for quality
        margin: 1,
        errorCorrectionLevel: 'M'
      })

      const qrImage = await pdfDoc.embedPng(qrBuffer)
      page.drawImage(qrImage, {
        x,
        y: y - QR_SIZE,
        width: QR_SIZE,
        height: QR_SIZE
      })

      // Serial number label below QR
      const snText = pageQrCodes[i].serial_number
      const textWidth = font.widthOfTextAtSize(snText, 7)
      page.drawText(snText, {
        x: x + (QR_SIZE - textWidth) / 2,
        y: y - QR_SIZE - LABEL_HEIGHT + 2,
        size: 7,
        font,
        color: rgb(0.3, 0.3, 0.3)
      })
    }

    // Footer
    const footerText = `Page ${pageIndex + 1} of ${totalPages} — Generated by Proofly`
    const footerWidth = font.widthOfTextAtSize(footerText, 8)
    page.drawText(footerText, {
      x: (A4_WIDTH - footerWidth) / 2,
      y: MARGIN - 20,
      size: 8,
      font,
      color: rgb(0.5, 0.5, 0.5)
    })
  }

  const pdfBytes = await pdfDoc.save()
  return Buffer.from(pdfBytes)
}
